name: CI

"on":
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

env:
  toolchain: nightly-2025-04-21
  CARGO_HTTP_MULTIPLEXING: false
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: true
  CARGO_INCREMENTAL: 0
  TERM: unknown

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: format
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.toolchain }}
          components: rustfmt
      - name: cargo format
        run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.toolchain }}
          components: clippy
      - name: Clippy
        run: |
          cargo clippy \
            --all-targets \
            -- -D warnings \
            -W clippy::pedantic \
            -W clippy::nursery \
            -W clippy::style \
            -W clippy::complexity \
            -W clippy::perf \
            -W clippy::suspicious \
            -W clippy::correctness
  toml-format:
    name: toml-format
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Taplo
        env:
          version: "0.9.3"
        run: |
          curl -Ls "https://github.com/tamasfe/taplo/releases/download/${{ env.version }}/taplo-full-linux-x86_64.gz" | \
          gzip -d > taplo && \
          chmod +x taplo && \
          sudo mv taplo /usr/local/bin/taplo
      - name: Run Taplo
        run: taplo fmt --check
